name: pricing_page
description: "A pre-made custom pricing page component. Easy for quick-setup of a ui charging your customers."
version: 1.0.0
repository: https://github.com/Go-Babel/pricing_page
issue_tracker: https://github.com/Go-Babel/pricing_page/issues
topics: [boilerplate, pre-made-ui, pricing]

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  animated_flip_counter: ^0.3.4
  collection: ^1.19.1
  dart_debouncer: ^1.1.1
  lottie: ^3.3.1
  babel_text: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

screenshots:
  - description: The pricing page package logo.
    path: assets/pricing_main_image.png